name: Windows RDP with AnyDesk

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Enable RDP
        shell: pwsh
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-Service -Name TermService -StartupType Automatic
          Start-Service TermService

      - name: Install AnyDesk (with unattended password)
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://download.anydesk.com/AnyDesk.exe" -OutFile "$env:TEMP\AnyDesk.exe"
          Start-Process "$env:TEMP\AnyDesk.exe" -ArgumentList "--install `"$env:ProgramFiles(x86)\AnyDesk`" --start-with-win --silent" -Wait
          # اضبط الباسورد للتوصيل بدون Accept
          & "$env:ProgramFiles(x86)\AnyDesk\AnyDesk.exe" --set-password "Anydeskpw07@"
          Start-Sleep -Seconds 5

      - name: Get AnyDesk ID
        id: anydesk
        shell: pwsh
        run: |
          $idFile = "$env:ProgramData\AnyDesk\system.conf"
          if (Test-Path $idFile) {
            $id = (Get-Content $idFile | Select-String "ad.anynet.id=" | ForEach-Object { $_ -replace "ad.anynet.id=", "" }).Trim()
            "ANYDESK_ID=$id" | Out-File -FilePath $env:GITHUB_ENV -Append
            Write-Host "AnyDesk ID: $id"
          } else {
            Write-Warning "AnyDesk ID file not found."
          }

      - name: Send AnyDesk info to Telegram
        shell: pwsh
        run: |
          $msg = "✅ Windows Cloud Ready (AnyDesk)`n`nAnyDesk ID: $env:ANYDESK_ID`nPassword: Anydeskpw07@`n`nNote: Session lasts 6h."
          $uri = "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
          curl -s -X POST $uri -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" --data-urlencode text="$msg"

      - name: Keep alive for 6h
        shell: pwsh
        run: Start-Sleep -Seconds 21600
