name: Windows RDP with RustDesk

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Enable RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
          net user runneradmin P@ssw0rd123!
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Install RustDesk
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://github.com/rustdesk/rustdesk/releases/latest/download/rustdesk.exe" -OutFile "$env:TEMP\rustdesk.exe"
          Start-Process "$env:TEMP\rustdesk.exe" -ArgumentList "/VERYSILENT" -Wait

      - name: Get RustDesk ID
        shell: powershell
        run: |
          Start-Sleep -Seconds 15
          $config = "$env:APPDATA\RustDesk\config\id_ed25519.pub"
          if (Test-Path $config) {
            $id = Get-Content $config
            echo "RUSTDESK_ID=$id" >> $env:GITHUB_ENV
            echo "RustDesk ID: $id"
          } else {
            echo "RustDesk config not found yet"
          }

      - name: Send Info to Telegram
        run: |
          $msg = @"
✅ Windows Cloud Ready (RustDesk)

RustDesk ID: $env:RUSTDESK_ID
User: runneradmin
Pass: P@ssw0rd123!

Note: Session lasts 6h.
"@
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" `
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} `
            --data-urlencode text="$msg"

      - name: Keep alive 6h
        run: Start-Sleep -Seconds 21600
